export const WELL_KNOWN_PORTS: Record<number, string> = {
  20: "FTP Data",
  21: "FTP",
  22: "SSH",
  23: "Telnet",
  25: "SMTP",
  53: "DNS",
  67: "DHCP",
  80: "HTTP",
  110: "POP3",
  143: "IMAP",
  443: "HTTPS",
  465: "SMTP (SSL)",
  587: "SMTP (TLS)",
  993: "IMAP (SSL)",
  995: "POP3 (SSL)",
  1433: "SQL Server",
  1521: "Oracle DB",
  2181: "Zookeeper",
  2375: "Docker",
  2376: "Docker (TLS)",
  3000: "Dev Server",
  3306: "MySQL",
  3307: "MySQL (Alt)",
  4200: "Angular Dev",
  4321: "Astro Dev",
  5000: "Dev Server",
  5173: "Vite",
  5432: "PostgreSQL",
  5433: "PostgreSQL (Alt)",
  5672: "RabbitMQ",
  5900: "VNC",
  6379: "Redis",
  6380: "Redis (Alt)",
  6443: "Kubernetes API",
  7000: "Dev Server",
  8000: "Dev Server",
  8080: "HTTP Alt",
  8081: "HTTP Alt",
  8443: "HTTPS Alt",
  8888: "Jupyter",
  9000: "Dev Server",
  9090: "Prometheus",
  9200: "Elasticsearch",
  9300: "Elasticsearch Transport",
  15672: "RabbitMQ Management",
  27017: "MongoDB",
  27018: "MongoDB (Alt)",
  28017: "MongoDB Web",
};

export const PROCESS_DESCRIPTIONS: Record<string, string> = {
  firefox: "Firefox",
  "google chrome": "Chrome",
  chrome: "Chrome",
  safari: "Safari",
  node: "Node.js",
  python: "Python",
  python3: "Python",
  ruby: "Ruby",
  java: "Java",
  postgres: "PostgreSQL",
  mysql: "MySQL",
  mysqld: "MySQL",
  redis: "Redis",
  "redis-server": "Redis",
  mongo: "MongoDB",
  mongod: "MongoDB",
  nginx: "Nginx",
  apache: "Apache",
  httpd: "Apache",
  code: "VS Code",
  electron: "Electron App",
  docker: "Docker",
  dockerd: "Docker",
  kubectl: "Kubernetes",
  logid: "Logitech Daemon",
  rapportd: "AirPlay / Handoff",
  controlce: "Control Center",
  coreaudio: "Core Audio",
  spotify: "Spotify",
  slack: "Slack",
  discord: "Discord",
  zoom: "Zoom",
  teams: "Microsoft Teams",
  php: "PHP",
  go: "Go",
  deno: "Deno",
  bun: "Bun",
};

export function getPortDescription(port: number, processName: string): string {
  const portDesc = WELL_KNOWN_PORTS[port];
  if (portDesc) return portDesc;

  const lower = processName.toLowerCase();
  for (const [prefix, desc] of Object.entries(PROCESS_DESCRIPTIONS)) {
    if (lower === prefix || lower.startsWith(prefix)) {
      return desc;
    }
  }

  return "";
}
