export type ProcessCategory = "system" | "background" | "app" | "dev";

export const CATEGORY_META: Record<
  ProcessCategory,
  { label: string; variant: "danger" | "warning" | "info" | "success" }
> = {
  system: { label: "System", variant: "danger" },
  background: { label: "Background", variant: "warning" },
  app: { label: "App", variant: "info" },
  dev: { label: "Dev", variant: "success" },
};

const PROCESS_CATEGORIES: Record<string, ProcessCategory> = {
  launchd: "system",
  mDNSResponder: "system",
  mds: "system",
  mds_stores: "system",
  distnoted: "system",
  notifyd: "system",
  rapportd: "system",
  sharingd: "system",
  coreaudiod: "system",
  coreaudio: "system",
  controlce: "system",
  ControlCenter: "system",
  WindowServer: "system",
  windowserver: "system",
  loginwindow: "system",
  kernel_task: "system",
  kerneltask: "system",
  SystemUIServer: "system",
  systemuiserver: "system",
  airportd: "system",
  configd: "system",
  opendirectoryd: "system",
  UserEventAgent: "system",
  usereventagent: "system",
  cfprefsd: "system",
  nsurlsessiond: "system",
  trustd: "system",
  syspolicyd: "system",
  tccd: "system",
  runningboardd: "system",
  powerd: "system",
  locationd: "system",

  // Background — daemons, kill with caution
  cupsd: "background",
  sshd: "background",
  avahi: "background",
  logid: "background",
  docker: "background",
  dockerd: "background",
  containerd: "background",
  "com.docker.backend": "background",
  postgres: "background",
  postgresql: "background",
  mysqld: "background",
  mysql: "background",
  mariadbd: "background",
  "redis-server": "background",
  redis: "background",
  mongo: "background",
  mongod: "background",
  kubectl: "background",
  minikube: "background",
  k3s: "background",
  k3d: "background",
  zookeeper: "background",
  rabbitmq: "background",
  "rabbitmq-server": "background",
  mosquitto: "background",
  prometheus: "background",
  grafana: "background",
  elasticsearch: "background",
  tailscaled: "background",
  syncthing: "background",
  adb: "background",
  ollama: "background",
  nginx: "background",
  apache: "background",
  httpd: "background",
  caddy: "background",
  traefik: "background",
  "php-fpm": "background",

  // App — user apps, safe to kill
  firefox: "app",
  "firefox helper": "app",
  "google chrome": "app",
  "google chrome helper": "app",
  chrome: "app",
  "chrome helper": "app",
  safari: "app",
  "safari networking": "app",
  spotify: "app",
  slack: "app",
  discord: "app",
  zoom: "app",
  teams: "app",
  "microsoft teams": "app",
  code: "app",
  "visual studio code": "app",
  "code helper": "app",
  electron: "app",
  "electron helper": "app",
  iterm2: "app",
  iterm: "app",
  terminal: "app",
  warp: "app",
  arc: "app",
  brave: "app",
  "brave browser": "app",
  opera: "app",
  whatsapp: "app",
  telegram: "app",
  signal: "app",
  notion: "app",
  figma: "app",
  postman: "app",
  insomnia: "app",
  obsidian: "app",

  // Dev — dev servers, safe to kill & restart
  node: "dev",
  npm: "dev",
  yarn: "dev",
  pnpm: "dev",
  vite: "dev",
  webpack: "dev",
  "webpack-dev-server": "dev",
  next: "dev",
  "next-server": "dev",
  nuxt: "dev",
  astro: "dev",
  bun: "dev",
  deno: "dev",
  python: "dev",
  python3: "dev",
  pythonw: "dev",
  uvicorn: "dev",
  gunicorn: "dev",
  ruby: "dev",
  rails: "dev",
  puma: "dev",
  java: "dev",
  gradle: "dev",
  mvn: "dev",
  go: "dev",
  air: "dev",
  php: "dev",
  artisan: "dev",
  dotnet: "dev",
  nodeemon: "dev",
  nodemon: "dev",
  tsx: "dev",
  "ts-node": "dev",
  "http-server": "dev",
  "live-server": "dev",
  jupyter: "dev",
  "jupyter-lab": "dev",
};

function normalizeProcessName(processName: string): string {
  return processName
    .toLowerCase()
    .trim()
    .replace(/\.exe$/i, "")
    .replace(/\s+\(.*?\)$/g, "")
    .replace(/\s+helper(\s*\(.+\))?$/g, " helper")
    .replace(/\.app$/g, "")
    .replace(/\s+/g, " ");
}

function findBestMatch<T>(processName: string, map: Record<string, T>): T | null {
  const normalized = normalizeProcessName(processName);

  if (map[normalized]) {
    return map[normalized];
  }

  for (const [prefix, value] of Object.entries(map)) {
    const normalizedPrefix = normalizeProcessName(prefix);
    if (
      normalized === normalizedPrefix ||
      normalized.startsWith(`${normalizedPrefix} `) ||
      normalized.includes(normalizedPrefix)
    ) {
      return value;
    }
  }

  return null;
}

export function getProcessCategory(
  processName: string,
): { label: string; variant: "danger" | "warning" | "info" | "success" } | null {
  const category = findBestMatch(processName, PROCESS_CATEGORIES);
  return category ? CATEGORY_META[category] : null;
}

export const WELL_KNOWN_PORTS: Record<number, string> = {
  20: "FTP Data",
  21: "FTP",
  22: "SSH",
  23: "Telnet",
  25: "SMTP",
  53: "DNS",
  67: "DHCP",
  68: "DHCP Client",
  80: "HTTP",
  110: "POP3",
  123: "NTP",
  137: "NetBIOS",
  138: "NetBIOS",
  139: "NetBIOS Session",
  143: "IMAP",
  161: "SNMP",
  389: "LDAP",
  443: "HTTPS",
  445: "SMB",
  465: "SMTP (SSL)",
  500: "IPsec / IKE",
  587: "SMTP (TLS)",
  631: "IPP / CUPS",
  993: "IMAP (SSL)",
  995: "POP3 (SSL)",
  1080: "SOCKS Proxy",
  1433: "SQL Server",
  1521: "Oracle DB",
  1883: "MQTT",
  2181: "Zookeeper",
  2375: "Docker",
  2376: "Docker (TLS)",
  3000: "Dev Server",
  3001: "Dev Server",
  3306: "MySQL",
  3307: "MySQL (Alt)",
  4000: "Dev Server",
  4200: "Angular Dev",
  4321: "Astro Dev",
  5000: "Dev Server",
  5432: "PostgreSQL",
  5433: "PostgreSQL (Alt)",
  5672: "RabbitMQ",
  5900: "VNC",
  5984: "CouchDB",
  6379: "Redis",
  6380: "Redis (Alt)",
  6443: "Kubernetes API",
  7000: "Dev Server",
  7001: "Dev Server",
  8000: "Dev Server",
  8001: "Dev Server",
  8080: "HTTP Alt",
  8081: "HTTP Alt",
  8443: "HTTPS Alt",
  8501: "Streamlit",
  8888: "Jupyter",
  9000: "Dev Server",
  9090: "Prometheus",
  9200: "Elasticsearch",
  9300: "Elasticsearch Transport",
  11434: "Ollama",
  15672: "RabbitMQ Management",
  27017: "MongoDB",
  27018: "MongoDB (Alt)",
  28017: "MongoDB Web",
};

export const PROCESS_DESCRIPTIONS: Record<string, string> = {
  firefox: "Firefox",
  "firefox helper": "Firefox",
  "google chrome": "Chrome",
  "google chrome helper": "Chrome",
  chrome: "Chrome",
  "chrome helper": "Chrome",
  safari: "Safari",
  brave: "Brave",
  "brave browser": "Brave",
  arc: "Arc",
  opera: "Opera",
  spotify: "Spotify",
  slack: "Slack",
  discord: "Discord",
  zoom: "Zoom",
  teams: "Microsoft Teams",
  "microsoft teams": "Microsoft Teams",
  whatsapp: "WhatsApp",
  telegram: "Telegram",
  signal: "Signal",
  notion: "Notion",
  figma: "Figma",
  postman: "Postman",
  insomnia: "Insomnia",
  iterm: "iTerm",
  iterm2: "iTerm",
  terminal: "Terminal",
  warp: "Warp",
  code: "VS Code",
  "visual studio code": "VS Code",
  "code helper": "VS Code",
  electron: "Electron App",
  "electron helper": "Electron App",
  node: "Node.js",
  npm: "npm",
  yarn: "Yarn",
  pnpm: "pnpm",
  vite: "Vite",
  webpack: "Webpack",
  "webpack-dev-server": "Webpack Dev Server",
  next: "Next.js",
  "next-server": "Next.js",
  nuxt: "Nuxt",
  astro: "Astro",
  python: "Python",
  python3: "Python",
  pythonw: "Python",
  uvicorn: "Uvicorn",
  gunicorn: "Gunicorn",
  ruby: "Ruby",
  rails: "Rails",
  puma: "Puma",
  java: "Java",
  gradle: "Gradle",
  mvn: "Maven",
  go: "Go",
  php: "PHP",
  "php-fpm": "PHP-FPM",
  dotnet: ".NET",
  postgres: "PostgreSQL",
  postgresql: "PostgreSQL",
  mysql: "MySQL",
  mysqld: "MySQL",
  mariadbd: "MariaDB",
  redis: "Redis",
  "redis-server": "Redis",
  mongo: "MongoDB",
  mongod: "MongoDB",
  nginx: "Nginx",
  apache: "Apache",
  httpd: "Apache",
  caddy: "Caddy",
  traefik: "Traefik",
  docker: "Docker",
  dockerd: "Docker",
  containerd: "Container Runtime",
  "com.docker.backend": "Docker",
  kubectl: "Kubernetes CLI",
  minikube: "Minikube",
  k3s: "K3s",
  k3d: "K3d",
  zookeeper: "Zookeeper",
  rabbitmq: "RabbitMQ",
  "rabbitmq-server": "RabbitMQ",
  prometheus: "Prometheus",
  grafana: "Grafana",
  elasticsearch: "Elasticsearch",
  adb: "Android Debug Bridge",
  ollama: "Ollama",
  jupyter: "Jupyter",
  "jupyter-lab": "JupyterLab",
  logid: "Logitech Daemon",
  rapportd: "AirPlay / Handoff",
  controlce: "Control Center",
  ControlCenter: "Control Center",
  coreaudio: "Core Audio",
  coreaudiod: "Core Audio",
  mDNSResponder: "Bonjour / DNS",
  sshd: "SSH Daemon",
  cupsd: "Print Service",
};

export function getPortDescription(port: number, processName: string): string {
  const portDesc = WELL_KNOWN_PORTS[port];
  if (portDesc) return portDesc;

  const desc = findBestMatch(processName, PROCESS_DESCRIPTIONS);
  return desc ?? "";
}